" Mappings for logdebug.vim
nmap <buffer> cl <Plug>LogDebugCL
nmap <buffer> l0 <Plug>LogDebugLog0
nmap <buffer> l1 <Plug>LogDebugLog1
nmap <buffer> l2 <Plug>LogDebugLog2
nmap <buffer> l3 <Plug>LogDebugLog3
nmap <buffer> l4 <Plug>LogDebugLog4
nmap <buffer> l5 <Plug>LogDebugLog5
nmap <buffer> l6 <Plug>LogDebugLog6
nmap <buffer> l7 <Plug>LogDebugLog7
nmap <buffer> l8 <Plug>LogDebugLog8
nmap <buffer> l9 <Plug>LogDebugLog9
